server:
  port: 8662
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: oracle
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    Properties:
      hibernate:
#          show_sql: true
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
